### ISSUE TITLE
FavorisService & FavorisMapper

### ISSUE THREAD

**Issue by PedroScocci** [colfrog/volos#17]
Service et Mappers des Favoris. Gère l'ajout d'annonce dans la liste des favoris d'un utilisateur et permet l'accès rapide à celle-ci.

**Comment by colfrog** [comment]
Ajouté avec 415171620b35ce6d1f0a3e729c2296e32d0a6afc, révisé par @IliassBour sur Teams devant l'équipe, il sera révisé à nouveau dans une pull request lorsque #15 sera mergé dans master.
