### ISSUE TITLE
Diagramme entité-relation

### ISSUE THREAD

**Issue by pauldrdlg** [colfrog/volos#4]

**Comment by colfrog** [comment]
![curious creature](https://user-images.githubusercontent.com/46326888/94605494-30e2f780-0267-11eb-864f-9e9ffdf30cd8.jpg)

**Comment by pauldrdlg** [comment]
![image (1)](https://user-images.githubusercontent.com/47032570/94605581-540da700-0267-11eb-9872-40bdb952702c.png)

**Comment by colfrog** [comment]
Révisé par l'équipe complète sur Teams
