### ISSUE TITLE
Page d'accueil

### ISSUE THREAD

**Issue by IliassBour** [colfrog/volos#7]
Page d'accueil du site web contenant, le prototype de page et les nouveautés d'annonces pour les catégories d'annonce

**Comment by colfrog** [comment]
9d405fc a rajouté le composant React de liste d'annonce. Il faut seulement l'intégrer à la page d'accueil et retravailler un peu le HTML et le CSS pour finir cette Issue.

**Comment by colfrog** [comment]
La page d'accueil est connectée aux services depuis 4d8acfddc68ec619bd7d93efbf83f3080895c3f5
